services:
  - type: web
    name: system-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask --app app db upgrade && gunicorn app:app --worker-class eventlet --workers 4 --timeout 240 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: system-db
          property: connectionString
      - key: SECRET_KEY
        value: "REPLACE_ME"  # replace with a strong, random value

# Provision a PostgreSQL database if needed
# Comment out the database block if you already have one
# in your Render account and just reference its name above.
databases:
  - name: system-db
    plan: free
