services:
  - type: web
    name: system-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --worker-class eventlet --bind 0.0.0.0:$PORT  # from Procfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: system-db
          property: connectionString
      - key: SECRET_KEY
        value: "REPLACE_ME"

# Provision a PostgreSQL database if needed
# Comment out the database block if you already have one
# in your Render account and just reference its name above.
databases:
  - name: system-db
    plan: free
